/**
 * Seed data for all dashboard tables.
 * All coordinates are in the Pontianak / Kalimantan Barat area.
 */

// ─── Poverty Households (poor_households) ────────────────────────────────────
const SEED_HOUSEHOLDS = [
  {
    head_name: "Budi Santoso",
    family_count: 5,
    poverty_level: "Extreme",
    latitude: -0.0263,
    longitude: 109.3425,
    notes: "Rumah semi-permanen, atap bocor",
    penghasilan: 800000,
    kondisi_rumah: 2,
    kepemilikan_aset: 1,
    fuzzy_score: 92.5,
    fuzzy_label: "SANGAT TINGGI",
  },
  {
    head_name: "Siti Aminah",
    family_count: 4,
    poverty_level: "Extreme",
    latitude: -0.0301,
    longitude: 109.3388,
    notes: "Janda, 3 anak sekolah",
    penghasilan: 600000,
    kondisi_rumah: 2,
    kepemilikan_aset: 2,
    fuzzy_score: 88.3,
    fuzzy_label: "SANGAT TINGGI",
  },
  {
    head_name: "Ahmad Hidayat",
    family_count: 6,
    poverty_level: "Miskin",
    latitude: -0.0195,
    longitude: 109.3501,
    notes: "Buruh harian lepas",
    penghasilan: 1200000,
    kondisi_rumah: 3,
    kepemilikan_aset: 3,
    fuzzy_score: 72.1,
    fuzzy_label: "TINGGI",
  },
  {
    head_name: "Dewi Lestari",
    family_count: 3,
    poverty_level: "Miskin",
    latitude: -0.0352,
    longitude: 109.3290,
    notes: "Pedagang kecil di pasar",
    penghasilan: 1500000,
    kondisi_rumah: 4,
    kepemilikan_aset: 3,
    fuzzy_score: 65.0,
    fuzzy_label: "TINGGI",
  },
  {
    head_name: "Rahmat Kurniawan",
    family_count: 7,
    poverty_level: "Extreme",
    latitude: -0.0410,
    longitude: 109.3460,
    notes: "Tinggal di bantaran sungai",
    penghasilan: 500000,
    kondisi_rumah: 1,
    kepemilikan_aset: 1,
    fuzzy_score: 95.8,
    fuzzy_label: "SANGAT TINGGI",
  },
  {
    head_name: "Nurul Hasanah",
    family_count: 2,
    poverty_level: "Miskin",
    latitude: -0.0180,
    longitude: 109.3550,
    notes: "Ibu rumah tangga, suami sakit",
    penghasilan: 900000,
    kondisi_rumah: 3,
    kepemilikan_aset: 2,
    fuzzy_score: 78.4,
    fuzzy_label: "TINGGI",
  },
  {
    head_name: "Hasan Basri",
    family_count: 4,
    poverty_level: "Rentan",
    latitude: -0.0225,
    longitude: 109.3610,
    notes: "Tukang ojek online",
    penghasilan: 2000000,
    kondisi_rumah: 5,
    kepemilikan_aset: 4,
    fuzzy_score: 45.2,
    fuzzy_label: "SEDANG",
  },
  {
    head_name: "Fatimah Zahra",
    family_count: 3,
    poverty_level: "Rentan",
    latitude: -0.0290,
    longitude: 109.3320,
    notes: "Penjahit rumahan",
    penghasilan: 1800000,
    kondisi_rumah: 5,
    kepemilikan_aset: 5,
    fuzzy_score: 38.6,
    fuzzy_label: "RENDAH",
  },
  {
    head_name: "Eko Prasetyo",
    family_count: 5,
    poverty_level: "Miskin",
    latitude: -0.0150,
    longitude: 109.3480,
    notes: "Nelayan kecil, pendapatan tidak tetap",
    penghasilan: 1100000,
    kondisi_rumah: 3,
    kepemilikan_aset: 2,
    fuzzy_score: 70.9,
    fuzzy_label: "TINGGI",
  },
  {
    head_name: "Yanti Suryani",
    family_count: 2,
    poverty_level: "Rentan",
    latitude: -0.0330,
    longitude: 109.3570,
    notes: "Pekerja warung makan",
    penghasilan: 2200000,
    kondisi_rumah: 6,
    kepemilikan_aset: 5,
    fuzzy_score: 28.4,
    fuzzy_label: "RENDAH",
  },
  {
    head_name: "Muhammad Rizki",
    family_count: 8,
    poverty_level: "Extreme",
    latitude: -0.0380,
    longitude: 109.3400,
    notes: "Pengangguran, 7 tanggungan",
    penghasilan: 400000,
    kondisi_rumah: 1,
    kepemilikan_aset: 1,
    fuzzy_score: 97.2,
    fuzzy_label: "SANGAT TINGGI",
  },
  {
    head_name: "Sri Wahyuni",
    family_count: 3,
    poverty_level: "Rentan",
    latitude: -0.0205,
    longitude: 109.3650,
    notes: "Guru honorer",
    penghasilan: 2500000,
    kondisi_rumah: 6,
    kepemilikan_aset: 6,
    fuzzy_score: 15.3,
    fuzzy_label: "TIDAK PRIORITAS",
  },
];

// ─── POI Markers (poi_markers) ───────────────────────────────────────────────
const SEED_POI = [
  { name: "Masjid Jami' Pontianak",        poi_type: "religion", religion_subtype: "mosque",   latitude: -0.0220, longitude: 109.3420, notes: "Masjid terbesar di pusat kota",     radius_meters: 500 },
  { name: "Gereja Katedral Pontianak",      poi_type: "religion", religion_subtype: "church",   latitude: -0.0245, longitude: 109.3380, notes: "Gereja bersejarah",                 radius_meters: 300 },
  { name: "Vihara Bodhisattva Karaniya",    poi_type: "religion", religion_subtype: "temple",   latitude: -0.0198, longitude: 109.3455, notes: "Vihara terbesar",                   radius_meters: 200 },
  { name: "Puskesmas Pontianak Selatan",    poi_type: "clinic",   religion_subtype: null,        latitude: -0.0310, longitude: 109.3350, notes: "Puskesmas utama kecamatan selatan", radius_meters: 1000 },
  { name: "Klinik Pratama Sehat Sentosa",   poi_type: "clinic",   religion_subtype: null,        latitude: -0.0270, longitude: 109.3500, notes: "Klinik 24 jam",                     radius_meters: 800 },
  { name: "Lumbung Pangan Desa Siantan",    poi_type: "food-bank",religion_subtype: null,        latitude: -0.0160, longitude: 109.3440, notes: "Distribusi beras untuk warga miskin",radius_meters: 1500 },
  { name: "SDN 01 Pontianak Barat",         poi_type: "school",   religion_subtype: null,        latitude: -0.0235, longitude: 109.3310, notes: "Sekolah dasar negeri",               radius_meters: 600 },
  { name: "SMP Negeri 3 Pontianak",         poi_type: "school",   religion_subtype: null,        latitude: -0.0180, longitude: 109.3520, notes: "SMP favorit",                       radius_meters: 700 },
];

// ─── Land Markers (land_markers) ─────────────────────────────────────────────
const SEED_LAND_MARKERS = [
  { name: "Tugu Khatulistiwa",             marker_type: "marker",    latitude: 0.0000,   longitude: 109.3228, notes: "Monumen landmark utama" },
  { name: "Kantor Gubernur Kalbar",        marker_type: "flag",      latitude: -0.0234,  longitude: 109.3412, notes: "Pusat pemerintahan provinsi" },
  { name: "Hutan Lindung Gunung Palung",   marker_type: "protected", latitude: -1.2100,  longitude: 110.1500, notes: "Kawasan hutan lindung nasional" },
  { name: "BPN Pontianak",                 marker_type: "registry",  latitude: -0.0280,  longitude: 109.3360, notes: "Kantor pertanahan kota" },
  { name: "Area Mangrove Kakap",           marker_type: "protected", latitude: -0.1050,  longitude: 109.1200, notes: "Zona konservasi mangrove" },
  { name: "Terminal Ambawang",             marker_type: "flag",      latitude: -0.0800,  longitude: 109.4100, notes: "Terminal bus utama" },
];

// ─── Land Shapes (land_shapes) ───────────────────────────────────────────────
const SEED_LAND_SHAPES = [
  {
    name: "Zona Permukiman Siantan",
    shape_type: "polygon",
    status: "Hak Milik",
    latitude: -0.0150,
    longitude: 109.3440,
    coordinates: JSON.stringify([
      [-0.0130, 109.3420], [-0.0130, 109.3460],
      [-0.0170, 109.3460], [-0.0170, 109.3420],
    ]),
    radius_meters: null,
    notes: "Kawasan permukiman padat penduduk",
  },
  {
    name: "Lahan Pertanian Rasau Jaya",
    shape_type: "polygon",
    status: "Hak Guna Usaha",
    latitude: -0.1500,
    longitude: 109.3800,
    coordinates: JSON.stringify([
      [-0.1450, 109.3750], [-0.1450, 109.3850],
      [-0.1550, 109.3850], [-0.1550, 109.3750],
    ]),
    radius_meters: null,
    notes: "Lahan pertanian padi, luas ~100 ha",
  },
  {
    name: "Area Industri Sei Raya",
    shape_type: "circle",
    status: "Hak Guna Bangunan",
    latitude: -0.0500,
    longitude: 109.3600,
    coordinates: null,
    radius_meters: 800,
    notes: "Kawasan industri ringan",
  },
  {
    name: "Jalan Tanjungpura",
    shape_type: "line",
    status: "Tanah Negara",
    latitude: -0.0250,
    longitude: 109.3400,
    coordinates: JSON.stringify([
      [-0.0200, 109.3350], [-0.0300, 109.3450],
    ]),
    radius_meters: null,
    notes: "Jalan arteri utama kota, panjang ~3 km",
  },
];

// ─── Gas Station Markers (gas_station_markers) ───────────────────────────────
const SEED_GAS_STATIONS = [
  {
    name: "SPBU 64.751.01 Pontianak",
    marker_category: "gas-pump",
    brand: "Pertamina",
    sub_type: null,
    gas_types: JSON.stringify(["Pertalite", "Pertamax", "Pertamina Dex", "Bio Solar"]),
    operating_hours: "24 Jam",
    status: null,
    latitude: -0.0230,
    longitude: 109.3390,
    notes: "SPBU utama di pusat kota",
  },
  {
    name: "SPBU 64.751.03 Ahmad Yani",
    marker_category: "gas-pump",
    brand: "Pertamina",
    sub_type: null,
    gas_types: JSON.stringify(["Pertalite", "Pertamax", "Bio Solar"]),
    operating_hours: "06:00 - 22:00",
    status: null,
    latitude: -0.0310,
    longitude: 109.3450,
    notes: "Dekat jalan Ahmad Yani",
  },
  {
    name: "SPBU 64.751.08 Siantan",
    marker_category: "gas-pump",
    brand: "Pertamina",
    sub_type: null,
    gas_types: JSON.stringify(["Pertalite", "Bio Solar"]),
    operating_hours: "06:00 - 21:00",
    status: null,
    latitude: -0.0155,
    longitude: 109.3520,
    notes: "SPBU kawasan Siantan",
  },
  {
    name: "Shell Gajah Mada",
    marker_category: "gas-pump",
    brand: "Shell",
    sub_type: null,
    gas_types: JSON.stringify(["Shell Super", "Shell V-Power", "Shell Diesel"]),
    operating_hours: "24 Jam",
    status: null,
    latitude: -0.0280,
    longitude: 109.3310,
    notes: "Shell pertama di Pontianak",
  },
  {
    name: "SPBU 64.751.12 Kubu Raya",
    marker_category: "gas-pump",
    brand: "Pertamina",
    sub_type: null,
    gas_types: JSON.stringify(["Pertalite", "Pertamax", "Bio Solar"]),
    operating_hours: "06:00 - 22:00",
    status: null,
    latitude: -0.0620,
    longitude: 109.3700,
    notes: "SPBU di kabupaten Kubu Raya",
  },
  {
    name: "EV Charging PLN Pontianak",
    marker_category: "charging-station",
    brand: null,
    sub_type: "Type 2 AC",
    gas_types: null,
    operating_hours: "24 Jam",
    status: "Active",
    latitude: -0.0240,
    longitude: 109.3430,
    notes: "Stasiun pengisian kendaraan listrik PLN",
  },
  {
    name: "EV Charging Mall Ayani Mega",
    marker_category: "charging-station",
    brand: null,
    sub_type: "CCS2 DC",
    gas_types: null,
    operating_hours: "10:00 - 22:00",
    status: "Active",
    latitude: -0.0335,
    longitude: 109.3470,
    notes: "Fast charging di basement mall",
  },
  {
    name: "Bengkel Pontianak Motor",
    marker_category: "wrench",
    brand: null,
    sub_type: null,
    gas_types: null,
    operating_hours: "08:00 - 17:00",
    status: null,
    latitude: -0.0260,
    longitude: 109.3480,
    notes: "Bengkel umum motor dan mobil",
  },
  {
    name: "Bengkel Jaya Abadi",
    marker_category: "wrench",
    brand: null,
    sub_type: null,
    gas_types: null,
    operating_hours: "08:00 - 18:00",
    status: null,
    latitude: -0.0190,
    longitude: 109.3560,
    notes: "Bengkel spesialis AC dan kelistrikan",
  },
];

module.exports = {
  SEED_HOUSEHOLDS,
  SEED_POI,
  SEED_LAND_MARKERS,
  SEED_LAND_SHAPES,
  SEED_GAS_STATIONS,
};
